runtime: python
entrypoint: gunicorn -b :$PORT main:app
threadsafe: on
env: flex

runtime_config: 
    python_version: 3
    
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
	# if running locally, see .env (source it)
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:orka587@/emix_dev?host=/cloudsql/emix-209309:europe-west3:emix
    APP_SETTINGS: >-
      config.DevelopmentConfig
beta_settings:
    cloud_sql_instances: emix-209309:europe-west3:emix